#!/bin/bash

# Install all project dependencies
pnpm add next@latest react@latest react-dom@latest @prisma/client@latest @mdx-js/loader@latest @mdx-js/react@latest @next-auth/prisma-adapter@latest @next/mdx@latest @prisma/client@latest @hookform/resolvers@latest @radix-ui/react-accordion@latest @radix-ui/react-alert-dialog@latest @radix-ui/react-aspect-ratio@latest @radix-ui/react-avatar@latest @radix-ui/react-checkbox@latest @radix-ui/react-dialog@latest @radix-ui/react-dropdown-menu@latest @radix-ui/react-label@latest @radix-ui/react-navigation-menu@latest @radix-ui/react-popover@latest @radix-ui/react-scroll-area@latest @radix-ui/react-select@latest @radix-ui/react-separator@latest @radix-ui/react-slot@latest @radix-ui/react-switch@latest @radix-ui/react-tabs@latest @radix-ui/react-toast@latest @react-email/button@latest @react-email/components@latest @react-email/html@latest @reduxjs/toolkit@latest @tabler/icons-react@latest @tailwindcss/line-clamp@latest @tanstack/react-table@latest @tiptap/extension-color@latest @tiptap/extension-link@latest @tiptap/extension-placeholder@latest @tiptap/extension-text-style@latest @tiptap/extension-underline@latest @tiptap/pm@latest @tiptap/react@latest @tiptap/starter-kit@latest @uidotdev/usehooks@latest class-variance-authority@latest clsx@latest cmdk@latest cookie@latest date-fns@latest framer-motion@latest next@latest next-redux-wrapper@latest next-themes@latest react@latest react-day-picker@latest react-dom@latest react-email@latest react-google-recaptcha@latest react-hook-form@latest react-redux@latest recharts@latest set-cookie-parser@latest sharp@latest tailwind-merge@latest tailwind-scrollbar-hide@latest tailwindcss-animate@latest use-places-autocomplete@latest validator@latest zod@latest next-auth@latest next-mdx-remote@latest  next-pwa@latest next-sitemap@latest  nookies@latest postcss-flexbugs-fixes@latest postcss-preset-env@latest  react-icons@latest react-markdown@latest rehype-autolink-headings@latest rehype-highlight@latest rehype-pretty-code@latest rehype-slug@latest remark-gfm@latest remove@latest bcryptjs@latest cloudinary@latest contentlayer@latest mongodb@latest moment@latest lucide-react@latest jsonwebtoken@latest highlight.js@latest --legacy-peer-deps


pnpm add --D @types/cookie@latest  @types/js-cookie@latest @types/node@latest @types/react@latest @types/react-draft-wysiwyg@latest @types/react-google-recaptcha@latest @types/set-cookie-parser@latest @types/validator@latest autoprefixer@latest cypress@latest eslint@latest eslint-config-next@latest eslint-plugin-react@latest eslint-plugin-react-hooks@latest postcss@latest postcss-simple-vars@latest prettier@latest prettier-plugin-tailwindcss@latest tailwindcss@latest typescript@latest @fullhuman/postcss-purgecss@latest @tailwindcss/aspect-ratio@latest @testing-library/dom@latest @testing-library/jest-dom@latest @testing-library/react@latest @testing-library/user-event@latest @types/bcryptjs@latest @types/jest@latest @types/mdx@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest babel-jest@latest eslint-plugin-jest@latest eslint-plugin-testing-library@latest husky@latest identity-obj-proxy@latest jest@latest lint-staged@latest msw@latest prisma@latest react-test-renderer@latest ts-jest@latest whatwg-fetch@latest  --legacy-peer-deps


echo "Dependencies installation completed!" 


